// Seed data: real herd export from ABCCMM (abccmm-plantel-26-07-2026.xlsx), report date 26/07/2026.
// Only core animal fields were reliable in the source sheet — breeding columns were placeholders
// ("NÃO ATIVAR O CAMPO" / generic "NOME"), so no Cobricao/Saude records are seeded.
const SEED_ANIMAIS = [
  { nome: "BENFICA DO COLORADO", sexo: "F", nascimento: "30/03/2013", registro: "0148328", pelagem: "CASTANHA", pai: "KONAN DA CATIMBA", mae: "SERESTA DO PORTO PALMEIRA" },
  { nome: "CARDEAL DO ALFAIATE", sexo: "M", nascimento: "22/06/2017", registro: "272747", pelagem: "ALAZÃ", pai: "FOGUETE CAXAMBUENSE", mae: "ZIRTANA DOS VARÕES" },
  { nome: "ESCOLARI DO CLÃ PADRÃO", sexo: "C", nascimento: "18/05/2002", registro: "8739", pelagem: "TORDILHA", pai: "PRATA XAPURI", mae: "URALITA A.J." },
  { nome: "FACEIRO CAPIM SANTO", sexo: "M", nascimento: "20/02/2019", registro: "062684", pelagem: "ALAZÃ", pai: "TRILHO DA ZIZICA", mae: "ILHA BELA JP" },
  { nome: "FESTA H.Z.", sexo: "F", nascimento: "14/11/2017", registro: "0185275", pelagem: "CASTANHA", pai: "URUTAU MEAÍPE", mae: "PRETA H.Z." },
  { nome: "FONTE AZUL SAFADO", sexo: "C", nascimento: "09/04/2017", registro: "20085", pelagem: "BAIA", pai: "FATOR DE ALCATÉIA", mae: "FONTE AZUL MAYA" },
  { nome: "FRANÇA AGÉO", sexo: "F", nascimento: "23/11/2017", registro: "0206029", pelagem: "ALAZÃ", pai: "ZEUS DA SANTA ESMERALDA", mae: "UVA ROSA DA SANTA ESMERALDA" },
  { nome: "GUERREIRO MUSSUREPE", sexo: "M", nascimento: "15/01/2020", registro: "075451", pelagem: "TORDILHA", pai: "ELDORADO DA BOA TERRA", mae: "MARABA FÁBULA" },
  { nome: "HELGA DO PAUDARCO", sexo: "F", nascimento: "12/01/2012", registro: "0180843", pelagem: "CASTANHA", pai: "ZEUS DOS TRÊS PODERES", mae: "DOMINIQUE DO PAUDARCO" },
  { nome: "ITAENGA RIBEIRA", sexo: "F", nascimento: "12/12/2014", registro: "0162897", pelagem: "CASTANHA", pai: "GUARITÁ SEARA DOURADA", mae: "SAUDADE BELA MARCHA" },
  { nome: "JASMIM DO MANP", sexo: "F", nascimento: "25/11/2016", registro: "0180844", pelagem: "TORDILHA", pai: "INVEJADO DO VALE DA PRATA", mae: "LIBERDADE DA VENEZA" },
  { nome: "JENIFER FTA", sexo: "F", nascimento: "25/03/2021", registro: "345442", pelagem: "LOBUNA", pai: "CORONEL TIJUCA", mae: "DIAMANTINA FTA" },
  { nome: "JENNIFER DO MANP", sexo: "F", nascimento: "15/12/2014", registro: "0164913", pelagem: "ALAZÃ", pai: "INVEJADO DO VALE DA PRATA", mae: "LOURINHA JOCAMAN" },
  { nome: "JUVENTUDE DA RAÇA", sexo: "F", nascimento: "27/11/2021", registro: "369592", pelagem: "ALAZÃ", pai: "FAVACHO ÉBANO II", mae: "BANDIDA FORUM" },
  { nome: "KÉFERA DOS BUGRES", sexo: "F", nascimento: "22/12/2018", registro: "0205678", pelagem: "CASTANHA", pai: "INVENCÍVEL CAXAMBUENSE", mae: "QUERMESSE MUG" },
  { nome: "LALA DO MANP", sexo: "F", nascimento: "15/12/2019", registro: "421010", pelagem: "ALAZÃ", pai: "MARABA ISTAMBUL", mae: "LOURINHA JOCAMAN" },
  { nome: "LOURINHA JOCAMAN", sexo: "F", nascimento: "04/01/2004", registro: "095219", pelagem: "ALAZÃ", pai: "DITADOR HERANÇA SM", mae: "CACHAÇA S.M." },
  { nome: "LUCY DO MANP", sexo: "F", nascimento: "31/05/2019", registro: "354714", pelagem: "ALAZÃ", pai: "MARABA ISTAMBUL", mae: "BENFICA DO COLORADO" },
  { nome: "LUMINOSO DOS BUGRES", sexo: "M", nascimento: "15/01/2020", registro: "285861", pelagem: "CASTANHA PAMPA", pai: "DELETE CAXAMBUENSE", mae: "HONDA DOS BUGRES" },
  { nome: "MAGO LUXOR", sexo: "C", nascimento: "20/12/2001", registro: "8740", pelagem: "TORDILHA", pai: "LAGLÓRIA GUALIBU", mae: "IDEOLOGIA V.S." },
  { nome: "MARABA FÁBULA", sexo: "F", nascimento: "10/01/2010", registro: "0114998", pelagem: "TORDILHA", pai: "A.R DOURADO", mae: "MARABÁ SILVANA" },
  { nome: "MARABA INRITI", sexo: "M", nascimento: "01/10/2013", registro: "039941", pelagem: "TORDILHA", pai: "VERMUTE JEA", mae: "MARABA FÁBULA" },
  { nome: "MARABA PAPATUDO", sexo: "M", nascimento: "09/10/2020", registro: "070609", pelagem: "BAIA", pai: "ELDORADO DA BOA TERRA", mae: "MARABA ILÍADA" },
  { nome: "MARABA QUATI", sexo: "M", nascimento: "02/02/2021", registro: "070608", pelagem: "BAIA", pai: "MESTRE FORMOSO 2S", mae: "MARABA GAIVOTA" },
  { nome: "MARABA QUIBOA", sexo: "F", nascimento: "25/02/2021", registro: "0240685", pelagem: "BAIA", pai: "MARABA LEGAT DE ALCATEIA", mae: "MARABA IDOLA" },
  { nome: "NIGERIA J.O.", sexo: "F", nascimento: "23/12/2007", registro: "0111158", pelagem: "ALAZÃ", pai: "AFRICANO DA BELA OLINDA", mae: "SAFIRA DO ZUMBI" },
  { nome: "RELÍQUIA DA MORRO ALTO", sexo: "F", nascimento: "17/01/2018", registro: "0189891", pelagem: "CASTANHA", pai: "ZICO DO YURI", mae: "OHANA DO CONFORTO" },
  { nome: "ROSEIRA DO PARAÍSO", sexo: "F", nascimento: "01/02/2014", registro: "0145938", pelagem: "ALAZÃ", pai: "LAREDO DO PARAÍSO", mae: "PRAIA DA MORADA NOVA" },
  { nome: "SIBÉRIA DO COLORADO", sexo: "F", nascimento: "11/11/2010", registro: "0132474", pelagem: "CASTANHA", pai: "ZEUS DOS TRÊS PODERES", mae: "GIGI DA VENEZA" },
  { nome: "TEIMOSA FAL", sexo: "F", nascimento: "20/09/2020", registro: "341748", pelagem: "PRETA", pai: "DUQUE DO ETAN", mae: "LUA NEGRA FAL" },
  { nome: "TIGRESA FAL", sexo: "F", nascimento: "16/11/2020", registro: "351686", pelagem: "CASTANHA PAMPA", pai: "PALHAÇO FAL", mae: "LAMPARINA FAL" },
  { nome: "TRAPAÇA BAVÁRIA", sexo: "F", nascimento: "27/10/2015", registro: "0181102", pelagem: "CASTANHA PAMPA", pai: "GALANTE DO EXPOENTE", mae: "VALENÇA DO PORTO PALMEIRA" },
];
